services:
  app:
    container_name: frontContainer
    image: frontApp:1.0
    restart: always
    ports:
      - 5000:5000
    networks:
      - red_ayra
      
networks:
  red_ayra:
    external: true