version: '3.8'
services:
  app:
    container_name: FrontAle
    image: ${DOCKER_IMAGE_NAME}:1.0
    restart: always
    ports:
      - 5000:5000
    networks:
      - red_ayra
      
networks:
  red_ayra:
    external: true