services:
  app:
    container_name: ${NAME_CONTAINER}
    image: ${NAME_IMAGE}:1.0
    restart: always
    ports:
      - 5000:5000
    networks:
      - red_ayra
      
networks:
  red_ayra:
    external: true